In [145]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.linear_model import LinearRegression
sns.set()

In [146]:
df = pd.read_excel("pdb dan pdrb.xlsx")
df.head()

tahun   kategori     penduduk  pendapatan_bruto
0   2004  Indonesia  225900000.0      2.295826e+15
1   2005  Indonesia  228800000.0      2.784960e+15
2   2006  Indonesia  231369500.0      3.338196e+15
3   2007  Indonesia  234900000.0      3.957404e+15
4   2008  Indonesia  237556400.0      4.951357e+15

In [151]:
df['kategori'] = df['kategori'].astype('category').cat.codes
df.head()

tahun  kategori     penduduk  pendapatan_bruto
0   2004         1  225900000.0      2.295826e+15
1   2005         1  228800000.0      2.784960e+15
2   2006         1  231369500.0      3.338196e+15
3   2007         1  234900000.0      3.957404e+15
4   2008         1  237556400.0      4.951357e+15

In [154]:
df_nan = df[df.isna().any(axis=1)]
df_nan.head()

tahun  kategori  penduduk  pendapatan_bruto
20   2024         1       NaN               NaN
21   2025         1       NaN               NaN
22   2026         1       NaN               NaN
23   2027         1       NaN               NaN
24   2028         1       NaN               NaN

In [224]:
df_clear = df.dropna()
df_clear['kategori'] = df_clear['kategori'].astype('category').cat.codes
df_clear = df_clear.reset_index(drop=True)
df_clear.head()

C:\Users\chesa\AppData\Local\Temp\ipykernel_25448\3116013501.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_clear['kategori'] = df_clear['kategori'].astype('category').cat.codes


tahun  kategori     penduduk  pendapatan_bruto
0   2004         1  225900000.0      2.295826e+15
1   2005         1  228800000.0      2.784960e+15
2   2006         1  231369500.0      3.338196e+15
3   2007         1  234900000.0      3.957404e+15
4   2008         1  237556400.0      4.951357e+15

# Penduduk Indonesia

In [257]:
x_id = df_clear.iloc[:20,:2]
y_pdid =df_clear.iloc[:20,2]
target_pdid = df.iloc[20:25,2]
x_pdid, y_pdid,target_pdid

(array([[2004,    1],
        [2005,    1],
        [2006,    1],
        [2007,    1],
        [2008,    1],
        [2009,    1],
        [2010,    1],
        [2011,    1],
        [2012,    1],
        [2013,    1],
        [2014,    1],
        [2015,    1],
        [2016,    1],
        [2017,    1],
        [2018,    1],
        [2019,    1],
        [2020,    1],
        [2021,    1],
        [2022,    1],
        [2023,    1]], dtype=int64),
 0     225900000.0
 1     228800000.0
 2     231369500.0
 3     234900000.0
 4     237556400.0
 5     241000000.0
 6     244000000.0
 7     247100000.0
 8     250200000.0
 9     253300000.0
 10    256200000.0
 11    259100000.0
 12    261900000.0
 13    264500000.0
 14    267100000.0
 15    269600000.0
 16    271900000.0
 17    273800000.0
 18    275500000.0
 19    277500000.0
 Name: penduduk, dtype: float64,
 20   NaN
 21   NaN
 22   NaN
 23   NaN
 24   NaN
 Name: penduduk, dtype: float64)

In [258]:
x_id = np.array(x_id)
y_pdid = np.array(y_pdid)

In [259]:
x_train, x_test, y_train, y_test = train_test_split(x_id, y_pdid, test_size=0.3, random_state=42)

In [260]:
from sklearn.linear_model import LinearRegression

model = LinearRegression()
model.fit(x_train, y_train)
y_pred = model.predict(x_test)
y_pred

array([2.27439426e+08, 2.74398849e+08, 2.68874211e+08, 2.30201745e+08,
       2.49537978e+08, 2.41251021e+08])

In [261]:
y_test

array([2.259e+08, 2.738e+08, 2.696e+08, 2.288e+08, 2.502e+08, 2.410e+08])

In [262]:
target_pdid.values.reshape(1,-1)

array([[nan, nan, nan, nan, nan]])

In [263]:
y_pred.shape

(6,)

In [264]:
pd_pred = df.iloc[20:25,:2]
pred = model.predict(pd_pred)
pred

C:\Users\chesa\anaconda3\Lib\site-packages\sklearn\base.py:432: UserWarning: X has feature names, but LinearRegression was fitted without feature names
  warnings.warn(


array([2.82685806e+08, 2.85448125e+08, 2.88210444e+08, 2.90972763e+08,
       2.93735082e+08])

In [265]:
from sklearn.metrics import mean_squared_error
mse = mean_squared_error(y_test, y_pred)
mse

953565938510.1588

# PDB Indonesia

In [267]:
y_pdbid = df_clear.iloc[:20,3]
y_pdbid = np.array(y_pdbid)

In [268]:
x_train, x_test, y_train, y_test = train_test_split(x_id, y_pdbid, test_size=0.3, random_state=42)

In [269]:
from sklearn.linear_model import LinearRegression

model = LinearRegression()
model.fit(x_train, y_train)
y_pred = model.predict(x_test)
y_pred

array([5.91046099e+14, 1.76513576e+16, 1.56442622e+16, 1.59459384e+15,
       8.61942800e+15, 5.60878479e+15])

In [270]:
y_test

array([2.29582620e+15, 1.69708000e+16, 1.51837304e+16, 2.78496040e+15,
       8.24186430e+15, 5.61344100e+15])

In [272]:
pdb_pred = df.iloc[20:25,:2]
pred = model.predict(pdb_pred)
pred

C:\Users\chesa\anaconda3\Lib\site-packages\sklearn\base.py:432: UserWarning: X has feature names, but LinearRegression was fitted without feature names
  warnings.warn(


array([2.06620009e+16, 2.16655486e+16, 2.26690963e+16, 2.36726441e+16,
       2.46761918e+16])

In [273]:
from sklearn.metrics import mean_squared_error
mse = mean_squared_error(y_test, y_pred)
mse

8.568453295096111e+29

# Penduduk Jakarta

In [280]:
x_jkt = df_clear.iloc[40:60,:2]
y_pdjkt = df_clear.iloc[40:60,2]
x_jkt,y_pdjkt

(    tahun  kategori
 40   2004         2
 41   2005         2
 42   2006         2
 43   2007         2
 44   2008         2
 45   2009         2
 46   2010         2
 47   2011         2
 48   2012         2
 49   2013         2
 50   2014         2
 51   2015         2
 52   2016         2
 53   2017         2
 54   2018         2
 55   2019         2
 56   2020         2
 57   2021         2
 58   2022         2
 59   2023         2,
 40     8792000.0
 41     8899000.0
 42     9005000.0
 43     9112000.0
 44     9215000.0
 45     9320000.0
 46     9607000.0
 47     9699000.0
 48     9791000.0
 49     9882000.0
 50     9974000.0
 51    10067000.0
 52    10177000.0
 53    10272000.0
 54    10363000.0
 55    10467000.0
 56    10560000.0
 57    10600000.0
 58    10730000.0
 59    10820000.0
 Name: penduduk, dtype: float64)

In [281]:
x_train, x_test, y_train, y_test = train_test_split(x_jkt, y_pdjkt, test_size=0.3, random_state=42)

In [282]:
from sklearn.linear_model import LinearRegression

model = LinearRegression()
model.fit(x_train, y_train)
y_pred = model.predict(x_test)
y_pred

array([ 8870090.20044544, 10676545.28582036, 10464021.15812919,
        8976352.26429105,  9720186.7112101 ,  9401400.51967338])

In [283]:
y_test

40     8792000.0
57    10600000.0
55    10467000.0
41     8899000.0
48     9791000.0
45     9320000.0
Name: penduduk, dtype: float64

In [289]:
pdjkt_pred = df.iloc[72:78,:2]
pred = model.predict(pdb_pred)
pred

array([10995331.47735712, 11101593.54120269, 11207855.60504827,
       11314117.66889384, 11420379.73273945])

# PDRB Jakarta

In [308]:
y_pdrbjkt = df_clear.iloc[40:60,3]

In [309]:
x_train, x_test, y_train, y_test = train_test_split(x_jkt, y_pdrbjkt, test_size=0.3, random_state=42)

In [310]:
from sklearn.linear_model import LinearRegression

model = LinearRegression()
model.fit(x_train, y_train)
y_pred = model.predict(x_test)
y_pred

array([-2.58975612e+14,  2.69413200e+15,  2.34670757e+15, -8.52634001e+13,
        1.13072209e+15,  6.09585449e+14])

In [311]:
y_test

40    3.659000e+14
57    2.961600e+15
55    2.480300e+15
41    4.084000e+14
48    9.592000e+14
45    6.832000e+14
Name: pendapatan_bruto, dtype: float64

In [312]:
pdrbjkt_pred = df.iloc[72:78,:2]
pred = model.predict(pdrbjkt_pred)
pred

array([3.21526863e+15, 3.38898085e+15, 3.56269306e+15, 3.73640527e+15,
       3.91011748e+15, 4.08382970e+15])

# Penduduk Kota Bandung

In [332]:
x_bdg = df_clear.iloc[20:40,:2]
y_pdbdg = df_clear.iloc[20:40,2]

In [333]:
x_train, x_test, y_train, y_test = train_test_split(x_bdg, y_pdbdg, test_size=0.3, random_state=42)

In [334]:
from sklearn.linear_model import LinearRegression

model = LinearRegression()
model.fit(x_train, y_train)
y_pred = model.predict(x_test)
y_pred

array([2338415.99109131, 2542312.1169265 , 2518324.33741648,
       2350409.88084633, 2434367.1091314 , 2398385.43986637])

In [335]:
y_test

20    2232620.0
37    2527854.0
35    2507888.0
21    2315890.0
28    2444617.0
25    2414700.0
Name: penduduk, dtype: float64

In [336]:
pdbdg_pred = df.iloc[46:52,:2]
pred = model.predict(pdbdg_pred)
pred

array([2578293.78619154, 2590287.67594655, 2602281.56570156,
       2614275.45545657, 2626269.34521158, 2638263.23496659])

# PDRB Kota Bandung

In [337]:
y_pdrbbdg = df_clear.iloc[20:40,3]

In [338]:
x_train, x_test, y_train, y_test = train_test_split(x_bdg, y_pdrbbdg, test_size=0.3, random_state=42)

In [339]:
from sklearn.linear_model import LinearRegression

model = LinearRegression()
model.fit(x_train, y_train)
y_pred = model.predict(x_test)
y_pred

array([-1.47124371e+13,  3.07926539e+14,  2.69969012e+14,  4.26632620e+12,
        1.37117669e+14,  8.01813794e+13])

In [340]:
y_test

20    2.742242e+13
37    2.971163e+14
35    2.884609e+14
21    3.479219e+13
28    1.319895e+14
25    7.028116e+13
Name: pendapatan_bruto, dtype: float64

In [341]:
pdrbbdg_pred = df.iloc[46:52,:2]
pred = model.predict(pdrbbdg_pred)
pred

array([3.64862829e+14, 3.83841592e+14, 4.02820356e+14, 4.21799119e+14,
       4.40777882e+14, 4.59756646e+14])

# Penduduk Kota Semarang

In [342]:
x_smg = df_clear.iloc[60:80,:2]
y_pdsmg = df_clear.iloc[60:80,2]

In [344]:
x_train, x_test, y_train, y_test = train_test_split(x_smg, y_pdsmg, test_size=0.3, random_state=42)

In [345]:
from sklearn.linear_model import LinearRegression

model = LinearRegression()
model.fit(x_train, y_train)
y_pred = model.predict(x_test)
y_pred

array([1387726.12917594, 1692227.5545657 , 1656403.85746102,
       1405637.97772828, 1531020.91759465, 1477285.37193763])

In [346]:
y_test

60    1352000.0
77    1660000.0
75    1659000.0
61    1363000.0
68    1582000.0
65    1407000.0
Name: penduduk, dtype: float64

In [349]:
pdsmg_pred = df.iloc[98:104,:2]
pred = model.predict(pdsmg_pred)
pred

array([1745963.10022271, 1763874.94877505, 1781786.79732739,
       1799698.64587973, 1817610.49443207, 1835522.34298441])

# PDRB Kota Semarang

In [350]:
y_pdrbsmg = df_clear.iloc[60:80,3]

In [353]:
x_train, x_test, y_train, y_test = train_test_split(x_smg, y_pdrbsmg, test_size=0.3, random_state=42)

In [354]:
from sklearn.linear_model import LinearRegression

model = LinearRegression()
model.fit(x_train, y_train)
y_pred = model.predict(x_test)
y_pred

array([-2.54407701e+13,  2.09203792e+14,  1.81598550e+14, -1.16381488e+13,
        8.49802005e+13,  4.35723365e+13])

In [355]:
y_test

60    2.030460e+13
77    2.048710e+14
75    1.913520e+14
61    2.320822e+13
68    5.438465e+13
65    3.846502e+13
Name: pendapatan_bruto, dtype: float64

In [356]:
pdsmg_pred = df.iloc[98:104,:2]
pred = model.predict(pdsmg_pred)
pred

array([2.50611656e+14, 2.64414278e+14, 2.78216899e+14, 2.92019520e+14,
       3.05822142e+14, 3.19624763e+14])

# Penduduk Kota Surabaya

In [363]:
x_srb = df_clear.iloc[100:120,:2]
y_pdsrb = df_clear.iloc[100:120,2]

In [364]:
x_train, x_test, y_train, y_test = train_test_split(x_srb, y_pdsrb, test_size=0.3, random_state=42)

In [365]:
from sklearn.linear_model import LinearRegression

model = LinearRegression()
model.fit(x_train, y_train)
y_pred = model.predict(x_test)
y_pred

array([2648323.80178174, 2975640.4766147 , 2937132.6325167 ,
       2667577.72383074, 2802355.17817372, 2744593.41202673])

In [366]:
y_test

100    2606000.0
117    2905000.0
115    2874314.0
101    2630000.0
108    2813000.0
105    2730000.0
Name: penduduk, dtype: float64

In [369]:
pdsrb_pred = df.iloc[150:157,:2]
pred = model.predict(pdsrb_pred)
pred

array([3033402.24276169, 3052656.16481069, 3071910.08685969,
       3091164.00890869, 3110417.93095768, 3129671.85300668])

# PDRB Kota Surabaya

In [370]:
y_pdrbsrb = df_clear.iloc[100:120,3]

In [371]:
x_train, x_test, y_train, y_test = train_test_split(x_srb, y_pdrbsrb, test_size=0.3, random_state=42)

In [372]:
from sklearn.linear_model import LinearRegression

model = LinearRegression()
model.fit(x_train, y_train)
y_pred = model.predict(x_test)
y_pred

array([2.99989644e+14, 7.84188010e+14, 7.27223497e+14, 3.28471901e+14,
       5.27847699e+14, 4.42400928e+14])

In [374]:
y_test

100    2.605000e+14
117    9.764000e+14
115    9.265000e+14
101    2.854000e+14
108    5.253000e+14
105    4.069000e+14
Name: pendapatan_bruto, dtype: float64

In [373]:
pdsrb_pred = df.iloc[150:157,:2]
pred = model.predict(pdsrb_pred)
pred

array([8.69634781e+14, 8.98117038e+14, 9.26599295e+14, 9.55081552e+14,
       9.83563808e+14, 1.01204607e+15])

# Penduduk Kota Medan

In [377]:
x_medan = df_clear.iloc[80:100,:2]
y_pdmedan = df_clear.iloc[80:100,2]

In [378]:
x_train, x_test, y_train, y_test = train_test_split(x_medan, y_pdmedan, test_size=0.3, random_state=42)

In [379]:
from sklearn.linear_model import LinearRegression

model = LinearRegression()
model.fit(x_train, y_train)
y_pred = model.predict(x_test)
y_pred

array([1977861.1481069 , 2417541.70193022, 2365814.57795101,
       2003724.71009652, 2184769.64402376, 2107178.95805494])

In [380]:
y_test

80    1990432.0
97    2470000.0
95    2435252.0
81    2036185.0
88    2168000.0
85    2102105.0
Name: penduduk, dtype: float64

In [386]:
pdmedan_pred = df.iloc[124:130,:2]
pred = model.predict(pdmedan_pred)
pred

array([2495132.38789903, 2520995.94988865, 2546859.51187825,
       2572723.07386786, 2598586.63585746, 2624450.19784707])

# PDRB Kota Medan

In [394]:
y_pdrbmedan = df_clear.iloc[80:100,3]

In [395]:
x_train, x_test, y_train, y_test = train_test_split(x_medan, y_pdrbmedan, test_size=0.3, random_state=42)

In [396]:
from sklearn.linear_model import LinearRegression

model = LinearRegression()
model.fit(x_train, y_train)
y_pred = model.predict(x_test)
y_pred

array([-9.35077951e+11,  1.97774981e+14,  1.74397327e+14,  1.07537491e+13,
        9.25755382e+13,  5.75090572e+13])

In [397]:
y_test

80    2.960000e+13
97    2.054000e+14
95    1.852000e+14
81    3.320000e+13
88    8.230000e+13
85    5.540000e+13
Name: pendapatan_bruto, dtype: float64

In [398]:
pdrbmedan_pred = df.iloc[124:130,:2]
pred = model.predict(pdmedan_pred)
pred

array([2.32841463e+14, 2.44530290e+14, 2.56219117e+14, 2.67907944e+14,
       2.79596771e+14, 2.91285598e+14])